# Generated by Django 3.0.3 on 2020-03-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200311_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='bath',
            new_name='baths',
        ),
        migrations.AddField(
            model_name='room',
            name='bedrooms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
