# Generated by Django 3.0.3 on 2020-03-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20200328_1808'),
        ('reservations', '0003_bookedday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedday',
            name='reservation',
        ),
        migrations.AddField(
            model_name='bookedday',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='booked_day', to='rooms.Room'),
            preserve_default=False,
        ),
    ]
