# Generated by Django 3.0.3 on 2020-03-28 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20200328_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedday',
            name='room',
        ),
        migrations.AddField(
            model_name='bookedday',
            name='reservation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='booked_day', to='reservations.Reservation'),
            preserve_default=False,
        ),
    ]
