# Generated by Django 3.0.3 on 2020-03-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='loaction',
            new_name='location',
        ),
    ]
