# Generated by Django 3.0.3 on 2020-03-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='room',
            field=models.ManyToManyField(to='rooms.Room'),
        ),
    ]
